# Generated by Django 2.2.16 on 2022-08-05 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220805_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='pub_date',
        ),
    ]
